---
# tasks file for dockapps
  - name: Install Dock Util for dock bar management
    package:
      name: dockutil
      state: present

  - name: Remove existing items from Dock
    command: dockutil --remove '{{ item }}'
    ignore_errors: true
    with_lines: dockutil --list | cut -f1

  - name: Add Apps to the Dock
    command: dockutil --add '{{ item }}'
    when: dockapps_apps is defined
    loop: '{{ dockapps_apps }}'

  - name: Add Folders to dock
    command: dockutil --add '{{ item.path }}' --view {{ item.view | default("fan") }} --display folder # --replacing {{ item.path | basename }}
    when: dockapps_folders is defined
    loop: '{{ dockapps_folders }}'
