---
# tasks file for dockapps
  - name: Install Dock Util for dock bar management
    package:
      name: dockutil
      state: present

  - name: Remove existing items from Dock
    shell: dockutil --remove '{{ item }}'
    ignore_errors: true
    with_lines: dockutil --list | cut -f1

  - name: Add Apps to the Dock
    shell: dockutil --add '{{ item }}'
    when: dockapps_apps is defined
    with_items: '{{ dockapps_apps }}'

  - name: Add Folders to dock
    shell: dockutil --find '{{ item.path }}' || dockutil --add '{{ item.path }}' --view {{ item.view | default("fan")}} --display folder
    when: dockapps_folders is defined
    with_items: '{{ dockapps_folders }}'
